### ISSUE TITLE
build order problem

### ISSUE THREAD

**Issue by kehw** [star-bnl/star-prop#18]
Many StRoot libraries need the tables to be generated first. I had multiple times that make tried to build a StRoot library before all the tables are generated, especially when I do parallel build. The building process stopped because of some missing table/header. The problem can be fixed by building the targets *_Tables first manually. Do you guys see such problem?

**Comment by plexoos** [comment]
This is supposed to be taken care of by scripts/dep_scan.py
See https://github.com/star-bnl/star-sw/blob/master/CMakeLists.txt#L96-L101
If there is a problem we should know how to reproduce it

**Comment by kehw** [comment]
I checked scripts/dep_scan.py. It requires python3, which is not available on RCF. I am using STAR pro. That means the dependence scan did not happen.

**Comment by plexoos** [comment]
yes, it seems to be the case

**Comment by kehw** [comment]
Is there a plan to install python3?

**Comment by plexoos** [comment]
You should ask the RACF support. They'd better install it centrally. I would definitely support this initiative.

**Comment by kehw** [comment]
We have python2 in OPTSTAR, which has a higher version than the system python2. Can you install a pyhon3 there as part of STAR tools.

**Comment by plexoos** [comment]
I remember searching for a relocatable rpm for python3 but could not find anything. If you have a better luck let me know. Otherwise, ask the farm support to install it centrally. It is the right way to do it for such a major application.

**Comment by plexoos** [comment]
also, you may want to ask them if it is already available on some cvmfs path

**Comment by kehw** [comment]
I just checked cvmfs. All builds them have require a higher version of gcc, which is not compatible with other parts of the STAR software. If we want to use this CMake system as the build system for STAR, it may not be a bad idea to make STAR tools self-contained.

**Comment by kehw** [comment]
We can try to build it from source files, if the relocatable rpm is not available.

**Comment by plexoos** [comment]
I did not get the point... You found python3 on cvmfs but don't want to use it because it is not compatible with the system default gcc? I must be really missing something...

To make STAR software self-contained is a great idea! That is why we initiated docker containers. Checkout the available Dockerfiles, they do use python3 from the official repositories. To use the containers on the farm one would just need to build singularity images from these Dockerfiles.

**Comment by kehw** [comment]
I thought those cvmfs python3 builds require putting a different version of gcc in PATH and LD_LIBRARY_PATH. I that case, it may cause problems with the STAR software, which is built with system default gcc. I just did a simple test with one version of cvmfs python3. It looks like I can just use it without loading a different gcc. I will let you know if I see any problem with is method.

**Comment by kehw** [comment]
ok, I picked up one build of python3 from cvmfs. Without changing my environment, like gcc and etc, I can use it for this CMake build. It looks like scripts/dep_scan.py worked as expected.

**Comment by plexoos** [comment]
Thanks for confirming
