### ISSUE TITLE
LOG4CXX_ROOT is not defined

### ISSUE THREAD

**Issue by kehw** [star-bnl/star-prop#2]
It looks like LOG4CXX_ROOT is not defined in my environment by default. Do we need to define it in addition to the standard STAR ENV?

**Comment by veprbl** [comment]
Yes

**Comment by plexoos** [comment]
You can specify it as an additional argument to cmake, e.g.

    cmake3 -DSTAR_SRC=../star-cvs -DLOG4CXX_ROOT=$OPTSTAR ....

**Comment by kehw** [comment]
$STAR_SRC goes to $STAR by default, which is set for all STAR users.
Maybe set the default of $LOG4CXX_ROOT to $OPTSTAR ?

**Comment by kehw** [comment]
ok, I did not noticed you are already doing that in the README.

**Comment by veprbl** [comment]
@kehw, I updated the instruction after @plexoos responded to you

**Comment by plexoos** [comment]
Let's close this issue if there are no more comments
