### ISSUE TITLE
RCAS build failure

### ISSUE THREAD

**Issue by klendathu2k** [star-bnl/star-prop#6]
Building under 64bits on rcas.  Compilation reaches 28%, then hits an unresolved dependency.

...

[ 28%] Building CXX object CMakeFiles/StiSsd.dir/star/simu/simu/jwebb/2019/11-19-2019-forward-git/star-cvs/StRoot/StiSsd/StiSsdDetectorBuilder.cxx.o
In file included from /star/simu/simu/jwebb/2019/11-19-2019-forward-git/star-cvs/StRoot/StSsdUtil/StSsdBarrel.hh:56:0,
                 from /star/simu/simu/jwebb/2019/11-19-2019-forward-git/star-cvs/StRoot/StiSsd/StiSsdDetectorBuilder.cxx:102:
/star/simu/simu/jwebb/2019/11-19-2019-forward-git/star-cvs/StRoot/StSsdUtil/StSsdWafer.hh:64:46: fatal error: tables/St_sdm_condition_db_Table.h: No such file or directory
 #include "tables/St_sdm_condition_db_Table.h"
                                              ^
compilation terminated.
make[2]: *** [CMakeFiles/StiSsd.dir/star/simu/simu/jwebb/2019/11-19-2019-forward-git/star-cvs/StRoot/StiSsd/StiSsdDetectorBuilder.cxx.o] Error 1
make[1]: *** [CMakeFiles/StiSsd.dir/all] Error 2
make: *** [all] Error 2

**Comment by plexoos** [comment]
how to reproduce please

**Comment by klendathu2k** [comment]
log into an rcas node, and follow the instructions for installing with cmake

On 11/19/19 2:33 PM, Dmitri Smirnov wrote:
> how to reproduce please
> 

-- 
.--- .-- . -... -... .--.-. -... -. .-.. .-.-.- --. --- ...-

**Comment by plexoos** [comment]
python3 is likely missing. Can you get it from somewhere? If not, I can send you instructions

**Comment by plexoos** [comment]
Given the experience with BirdView I think it may take a very long time before we get python3 on RCAS nodes... Meanwhile, I have python3 installed in my home area, so you can just add `/star/u/smirnovd/usr/local/bin/` to your PATH

**Comment by plexoos** [comment]
close due to inactivity
